apiVersion: v1
kind: Service
metadata:
  name: nosdeux-api
  namespace: default
spec:
  selector:
    app: nosdeux-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081   # Access via http://<pi-tailscale-ip>:30081
