apiVersion: apps/v1
kind: Deployment
metadata:
  name: nousdeux
  namespace: default
  labels:
    app: nousdeux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nousdeux
  template:
    metadata:
      labels:
        app: nousdeux
    spec:
      containers:
        - name: nousdeux
          image: registry.tail32699d.ts.net/nousdeux:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "200m"
